model_type: udop
dataset_type: infographicsvqa
dataset: infographicsvqa_merged_train.jsonl
val_dataset: infographicsvqa_merged_val.jsonl
images_dir: infographicsvqa/infographicsvqa_images
batch_size: 8
max_length: 512
epochs: 10
learning_rate: 5e-5
output_dir: outputs/test_udop_infographicsvqa/ 