model_type: udop
dataset_type: spdocvqa
dataset: spdocvqa_merged_train.jsonl
val_dataset: spdocvqa_merged_val.jsonl
images_dir: spdocvqa/spdocvqa_images
batch_size: 8
max_length: 512
epochs: 10
learning_rate: 5e-5
output_dir: outputs/test_udop_spdocvqa/ 